name: opy # you probably want to 'snapcraft register <name>'
#base: core18
version: 'latest' # just for humans, typically '1.2+git' or '1.3.2'
summary: Onelinerers' Python, which works like AWK # 79 char long summary
description: |
  This command works like AWK in one liners. It enables you to use Python
  modules on CLI.


grade: stable
confinement: strict

apps:
  opy:
    command: opy

parts:
  opy:
    source: https://github.com/ryuichiueda/opy.git
    plugin: dump
    source-tag: master
    source-depth: 1

