name: oneliner-python # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.4.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: Onelinerers' Python, which works like AWK # 79 char long summary
description: |
  Opy works like AWK in one liners. It enables you to use Python modules
  on CLI.


grade: stable
confinement: strict

parts:
  opy:
    plugin: make
    source: https://github.com/ryuichiueda/opy.git
    source-type: git
    source-tag: master
    source-depth: 1
    build-packages: [man]

layout:
  /usr/local/bin/opy:
    bind: $SNAP/usr/local/bin/opy
  /usr/local/share/man:
    bind: $SNAP/usr/local/share/man
    bind: $SNAP/usr/local/bin/opy
